### ISSUE TITLE
Feature: Add mapped volumes to docker-compose

### ISSUE THREAD

**Issue by BackedUpBooty** [scale8/scale8-tag-manager-and-analytics#112]
**Is your feature request related to a problem? Please describe.**
If the containers are removed, recreated or migrated then all tag/analytics information is lost.

**Describe the solution you'd like**
Volume mappings which allows for mapped folders and data to be hosted as per the user's requirements for db/login/tag and platform info migration if/when necessary, something like:

```
mongodb:
  volumes:
    - ./data:/data
```

**Describe alternatives you've considered**
Not sure what other container folders may need to be mapped so various configs persist

**Additional context**

**Comment by cwbeck** [comment]
@BackedUpBooty - we're going to provide a number of self-hosted options/examples via docker-compose and Terraform.

Thank you for submitting the issue, but I'm going to close this out as it is now firmly on our roadmap.

**Comment by BackedUpBooty** [comment]
Understood, thanks for letting me know. I took a look through the repo, have you published a road map? I'd really like to keep up to date with this project.

**Comment by cwbeck** [comment]
@BackedUpBooty - internally yes, externally no. We had a rough [high-level roadmap on our old README](https://github.com/scale8/scale8-tag-manager-and-analytics/blob/31ecf44e0783265f79296931ac5cdd9e687b6749/README.md), but we have made changes (actually based on customer feedback!) and we are going to re-share it in a more structured way and perhaps using GitHub projects.

I'd '**_watch_**' the repo for updates, we push releases out and detail changes there. You can also follow us on twitter [twitter.com/scale8_com](https://twitter.com/scale8_com).

If you have any immediate requirements or suggestions though, we'd love to hear them. We've enabled discussions in the repo for exactly this. Our hope is features will get requested, upvoted and easier to prioritise. 💡
